//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleTable()
        {
            this.PersonalInfo = new HashSet<PersonalInfo>();
            this.ScheduleFile = new HashSet<ScheduleFile>();
        }
    
        public int ScheduleCode { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public string Uploader { get; set; }
        public string ScheduleFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInfo> PersonalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleFile> ScheduleFile { get; set; }
        public virtual ScheduleTable ScheduleTable1 { get; set; }
        public virtual ScheduleTable ScheduleTable2 { get; set; }
        public virtual ScheduleTable ScheduleTable11 { get; set; }
        public virtual ScheduleTable ScheduleTable3 { get; set; }
    }
}
