//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleFileCon", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class ScheduleFileCon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dayValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int scheduleCodeValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan timeValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weekValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dayValue {
            get {
                return this.dayValueField;
            }
            set {
                if ((object.ReferenceEquals(this.dayValueField, value) != true)) {
                    this.dayValueField = value;
                    this.RaisePropertyChanged("dayValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idValue {
            get {
                return this.idValueField;
            }
            set {
                if ((this.idValueField.Equals(value) != true)) {
                    this.idValueField = value;
                    this.RaisePropertyChanged("idValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int scheduleCodeValue {
            get {
                return this.scheduleCodeValueField;
            }
            set {
                if ((this.scheduleCodeValueField.Equals(value) != true)) {
                    this.scheduleCodeValueField = value;
                    this.RaisePropertyChanged("scheduleCodeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan timeValue {
            get {
                return this.timeValueField;
            }
            set {
                if ((this.timeValueField.Equals(value) != true)) {
                    this.timeValueField = value;
                    this.RaisePropertyChanged("timeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weekValue {
            get {
                return this.weekValueField;
            }
            set {
                if ((object.ReferenceEquals(this.weekValueField, value) != true)) {
                    this.weekValueField = value;
                    this.RaisePropertyChanged("weekValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSchedule", ReplyAction="http://tempuri.org/IService1/GetScheduleResponse")]
        UserInterface.ServiceReference1.ScheduleFileCon[] GetSchedule(System.Nullable<int> scheduleCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSchedule", ReplyAction="http://tempuri.org/IService1/GetScheduleResponse")]
        System.Threading.Tasks.Task<UserInterface.ServiceReference1.ScheduleFileCon[]> GetScheduleAsync(System.Nullable<int> scheduleCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UserInterface.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UserInterface.ServiceReference1.IService1>, UserInterface.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UserInterface.ServiceReference1.ScheduleFileCon[] GetSchedule(System.Nullable<int> scheduleCode) {
            return base.Channel.GetSchedule(scheduleCode);
        }
        
        public System.Threading.Tasks.Task<UserInterface.ServiceReference1.ScheduleFileCon[]> GetScheduleAsync(System.Nullable<int> scheduleCode) {
            return base.Channel.GetScheduleAsync(scheduleCode);
        }
    }
}
